# Generated by Django 4.2.1 on 2023-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('0', 'Admin'), ('1', 'Doctor'), ('2', 'Nurse'), ('3', 'Worker')], default='3', max_length=5),
        ),
    ]
