# Generated by Django 4.2.1 on 2023-05-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('worker', 'Worker'), ('admin', 'Admin')], max_length=30),
        ),
    ]
