# Generated by Django 4.2.1 on 2023-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usertype_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('Dentistry', 'Dentistry'), ('Ear, nose and throat (ENT)', 'Ear, nose and throat (ENT)'), ('General surgery', 'General surgery'), ('Internal Medicine', 'Internal Medicine'), ('Ophthalmology', 'Ophthalmology'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('General Practitioner', 'General Practitioner')], default='General Practitioner', max_length=30),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('worker', 'Worker'), ('admin', 'Admin')], default='worker', max_length=30),
        ),
    ]
